### PR TITLE
Add objects and classes for posts and pools

### PR DESCRIPTION
**Pull request by Hunter-The-Furry**
Figured I would lend a hand here after seeing this in the TODO. @BugadinhoGamers I assume this is what you meant by that, if not just let me know.

### CODE REVIEW

**Comment by Bugadinho** [comment]
Not exactly what i meant, poor wording on my part there, right now, all of the functions that returns posts return a list, preferably, it should return a Post object containing the data, same goes for the getPool function, it should return a pool object. 

So instead of post["file"]["url"] it would be post.file.url, for example.

**Comment by Hunter-The-Furry** [comment]
There we go, that should do it.

**Comment by Bugadinho** [comment]
That's exactly what i wanted, i'll do some tests on it afterwards, however, one small thing which maybe can be improved is the dependency on munch, otherwise, it looks great.

**Comment by Hunter-The-Furry** [comment]
There might be something I can do about that dependency, I can look into it tomorrow if you'd like.

**Comment by Bugadinho** [comment]
If possible, that would be ideal

**Comment by Hunter-The-Furry** [comment]
I know I said "tomorrow" but I figured I could get this done real quick. I tried a couple of different ways but ended up finding [this](https://stackoverflow.com/a/31569634/14422669) which worked great.

**Comment by Bugadinho** [comment]
This looks great, did some tests and stuff seems to be working fine, will work as a solid base for the other object based stuff i have planned for later on.

**Pull request merged**
